### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by centurionj** [centurionj/solana-treider-bot#1]
**БД**

- [ ] Таблица WalletAddress (адреса кошельков)
- [ ] Таблица WalletAddressFile (singletone для загрузки txt файла)
- [ ] Парсинг данных в таблицу WalletAddress из файла в модели WalletAddressFile 

**АДРЕСА КОШЕЛЬКОВ**
- [ ] Получение адресов кошельков
- [ ] Получение инфы о кошельке
- [ ] Фильтрация кошельков
- [ ] Celery и Celery Beat для автоматизации (запрос раз в 3 секунды)

**ИНФА О ТРАНЗАКЦИЯХ**
- [ ] Мониторинг покупок кошельков из бд
- [ ] Celery и Celery Beat для автоматизации (запрос раз в 3 секунды)

- [ ] Созвон с Васей для получения дальнейших указаний (узнать в каком виде и куда передавать данные)

**РАЗВЕРТЫВАНИЕ**
- [ ] Docker и docker-compose (добавить Celery и Celery Beat)

**ИНСТРУКЦИЯ**
- [ ] Инструкция

**ТЕСТИРОВАНИЕ В СВОЕМ ПОЛЬЗОВАНИИ**
- [ ] Деплой
- [ ] Тесты

**РЫНОК**
- [ ] Выход на рынок?
